from __future__ import annotations

from enum import IntEnum
from math import radians


SCREEN_W = 393
SCREEN_H = 852
FPS = 60
DT = 1.0 / FPS

TOP_UI_HEIGHT = 56
BOTTOM_UI_HEIGHT = 80
VIEWPORT_X = 0
VIEWPORT_Y = TOP_UI_HEIGHT
VIEWPORT_W = SCREEN_W
VIEWPORT_H = SCREEN_H - TOP_UI_HEIGHT - BOTTOM_UI_HEIGHT

GROUND_Y = 0.0
WORLD_UP_Y = 1.0

STAGE_MIN_X = -480.0
STAGE_MAX_X = 480.0
STAGE_MIN_Y = 0.0
STAGE_MAX_Y = 100.0
STAGE_MIN_Z = -60.0
STAGE_MAX_Z = 180.0
STAGE_CHUNK_SIZE_X = 90.0


class LaneId(IntEnum):
    NEGATIVE_Z = 0
    CENTER = 1
    POSITIVE_Z = 2


LANE_Z = (-36.0, 0.0, 36.0)
LANE_COUNT = len(LANE_Z)
LANE_HALF_LIFE = 0.055
LANE_SNAP_EPSILON = 0.05
LANE_MAPPING_SWITCH_THRESHOLD_PX = 8.0
MOVE_MAPPING_SWITCH_THRESHOLD_PX = 8.0
LANE_TURN_DELAY_SECONDS = 0.10

PLAYER_SIZE_X = 18.0
PLAYER_SIZE_Y = 30.0
PLAYER_SIZE_Z = 16.0
PLAYER_MAX_SPEED = 72.0
PLAYER_ACCELERATION = 480.0
PLAYER_DECELERATION = 520.0
PLAYER_START_X = 0.0
PLAYER_START_LANE = LaneId.CENTER
PLAYER_START_FACING = 1
TURN_HALF_LIFE = 0.04
PLAYER_MOVE_READY_RADIANS = radians(12.0)
RIVER_START_Z = LANE_Z[-1] + PLAYER_SIZE_Z * 0.5

VISIBLE_SIZE_X = 180.0
VISIBLE_SIZE_Y = 100.0
VISIBLE_SIZE_Z = STAGE_MAX_Z - STAGE_MIN_Z


class CameraShotId(IntEnum):
    REAR_RIGHT_LOW = 0
    FRONT_RIGHT_CLOSE = 1
    REAR_LEFT_SHALLOW = 2


INITIAL_CAMERA = CameraShotId.REAR_RIGHT_LOW
CAMERA_TARGET_Y = 18.0
CAMERA_FOLLOW_LAG_X = 0.0
CAMERA_FOLLOW_LAG_Z = 0.0
CAMERA_TRANSITION_SECONDS = 0.85
HORIZONTAL_FOV = 38.0
NEAR_PLANE = 4.0

CAMERA_SHOT_SPECS = {
    CameraShotId.REAR_RIGHT_LOW: (
        radians(110.0),
        radians(12.0),
        640.0,
        CAMERA_TARGET_Y,
    ),
    CameraShotId.FRONT_RIGHT_CLOSE: (
        radians(70.0),
        radians(14.0),
        520.0,
        CAMERA_TARGET_Y,
    ),
    CameraShotId.REAR_LEFT_SHALLOW: (
        radians(240.0),
        radians(6.0),
        700.0,
        CAMERA_TARGET_Y,
    ),
}


class RenderLayer(IntEnum):
    BACKGROUND = 0
    FLOOR = 10
    FLOOR_GUIDE = 20
    SOLID = 30
    DEBUG_VOLUME = 40
    HUD = 100


TAP_MAX_SECONDS = 0.25
TAP_MAX_DISTANCE = 10.0
STICK_DEAD_ZONE_PX = 18.0
STICK_LANE_STEP_PX = 64.0
STICK_LANE_REPEAT_DELAY_SECONDS = 0.16
STICK_UI_RADIUS = 30
STICK_UI_KNOB_RADIUS = 7

PLAYER_OBJECT_ID = -100
FLOOR_OBJECT_ID = -200
RIVER_OBJECT_ID = -210
VISIBLE_VOLUME_OBJECT_ID = -300
INSPECTABLE_OBJECT_ID_BASE = 10000
ENVIRONMENT_OBJECT_ID_BASE = 20000

INSPECTION_PROMPT_HALF_W = 5
INSPECTION_PROMPT_HEIGHT = 7
INSPECTION_PROMPT_HIT_W = 40
INSPECTION_PROMPT_HIT_H = 40
INSPECTION_PANEL_X = 12
INSPECTION_PANEL_Y = 536
INSPECTION_PANEL_W = 369
INSPECTION_PANEL_H = 204
INSPECTION_PANEL_PADDING_X = 16
INSPECTION_PANEL_PADDING_TOP = 14
INSPECTION_PANEL_PADDING_BOTTOM = 14
INSPECTION_FONT_PATH = "assets/fonts/DotGothic16-Regular.ttf"
INSPECTION_TITLE_FONT_SIZE = 16
INSPECTION_BODY_FONT_SIZE = 15
INSPECTION_TEXT_MAX_WIDTH = INSPECTION_PANEL_W - INSPECTION_PANEL_PADDING_X * 2
INSPECTION_TEXT_LINE_HEIGHT = 19
INSPECTION_TITLE_LINE_HEIGHT = 20
INSPECTION_TEXT_MAX_LINES = 6

CULL_EPSILON = 1e-5

TARGET_CANDIDATE_OBJECTS = 30
WARNING_CANDIDATE_OBJECTS = 60
TARGET_VISIBLE_FACES = 120
WARNING_VISIBLE_FACES = 240
TARGET_DRAW_TRIANGLES = 240
WARNING_DRAW_TRIANGLES = 480
TARGET_DRAW_LINES = 180
WARNING_DRAW_LINES = 360
TARGET_CLIPPED_BOXES = 12
WARNING_CLIPPED_BOXES = 24
