from __future__ import annotations


BACKGROUND = 1
UI_PANEL = 0
UI_PANEL_ALT = 5
UI_TEXT = 7
UI_MUTED = 13
UI_ACTIVE = 10
UI_WARNING = 8

FLOOR_FILL = 3
FLOOR_OUTLINE = 13
RIVER_FILL = 12
RIVER_OUTLINE = 6
LANE_LINE = 12
LANE_TICK = 6
VOLUME_EDGE = 7
PLAYER_OUTLINE = 0
INSPECTABLE_SIDE = 5
INSPECTABLE_TOP = 10
INSPECTABLE_OUTLINE = 0
INSPECTION_PROMPT_FILL = 10
INSPECTION_PROMPT_OUTLINE = 0
INSPECTION_PANEL_SHADOW = 5
INSPECTION_PANEL_FILL = 0
INSPECTION_PANEL_BORDER = 7
INSPECTION_PANEL_TITLE = 10
INSPECTION_PANEL_TITLE_SHADOW = 0
INSPECTION_PANEL_TEXT = 7
INSPECTION_PANEL_MUTED = 13
